version: '3'
services:
  app:
    build: .
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    environment:
      - S3_URL=http://rustfs:9000
      - S3_ACCESS_KEY=rustfsadmin
      - S3_SECRET_KEY=rustfskey
      - S3_BUCKET=cache
      - S3_REGION="ap-northeast-1"
      - S3_PATH_STYLE=true
      - REDIS_URL=redis://valkey:6379
      - BIND_ADDR=0.0.0.0:8088
      - BASE_URL=localhost:8088
    ports:
      - 8088:8088
  valkey:
    image: valkey/valkey:9-alpine
    restart: always
    volumes:
      - ./valkey:/data
  rustfs:
    image: rustfs/rustfs:latest
    restart: always
    volumes:
      - ./rustfs:/data
      - ./rustfs-logs:/logs
    ports:
      - 9001:9001
    environment:
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfskey
      - RUSTFS_CONSOLE_ENABLE=true

